pipeline:
  publish:
    image: quay.io/presslabs/bfc:latest
    pull: true
    environment:
      - ORIGIN_REPO=https://github.com/presslabs/wordpress.git
      - GIT_USER=presslabs-bot
      - GIT_EMAIL=bot@presslabs.com
    secrets: [GIT_PASSWORD]
    commands:
      - ./setup-github-credentials.sh
      - make
    when:
      event: push
      branch: master
